on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Simple job to say hello
    steps:
      - name: Hello world step
        id: hello
        uses: pabloVinicius/hello-world-javascript-action@v1.1
        with:
          who-to-greet: 'Pabloww'
      - name: Get the hello world output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
