on:
  pull_request:
    types: [opened]
    branches:
      - staging

jobs:
  build_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: Generate changelog
        id: changelog-builder
        uses: pabloVinicius/release-builder@v0.7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Commit changelog file
        uses: EndBug/add-and-commit@v9
        with:
          message: Update changelog
          default_author: github_actions
